export const products = [
    {
      id: 1,
      image: "/images/products1.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
    {
      id: 2,
      image: "/images/product2.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Disabled",
    },
    {
      id: 3,
      image: "/images/product3.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
    {
      id: 4,
      image: "/images/products1.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
    {
      id: 5,
      image: "/images/product2.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
    {
      id: 6,
      image: "/images/product3.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Disabled",
    },
    {
      id: 7,
      image: "/images/products1.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Disabled",
    },
    {
      id: 8,
      image: "/images/product2.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
    {
      id: 9,
      image: "/images/product3.svg",
      name: "Mercedes",
      price: 124000.0,
      sold: 1,
      earning: 14676.0,
      status: "Available",
    },
  ];